name: studio_export
suite: Resonance
tagline: "Ship it, signed"
does: render
server: l7-gateway
mcp_tool: studio.export
description: "Records and exports audio/video from the studio. All exports are watermarked with creator attribution — Alberto Valido Delgado, autogenerated, timestamped. No pseudonyms. Clear provenance."
needs:
  format: string
  quality: string
  watermark: boolean
gives:
  file_path: string
  duration: number
  hash: string
  registry_id: string
pii: false
approval: false
audit: true
output: json
runs: once
version: v1
icon: download
color: "#ec4899"
patent: "Integrated Audio-Visual Synthesis Engine"
inventor: "Alberto Valido Delgado"
